platform :ios, '10.0'
use_frameworks!

target 'road' do
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'

  pod 'RCT3DModel', :path => '../node_modules/react-native-3d-model-view'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'



  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'


  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

end